name: Build

on:
  push:
    branches:
      - main

jobs:
  # x86_64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@v4
  #       with:
  #         extra-conf: |
  #           extra-substituters = s3://muck-intromit-lizard?endpoint=https://storage.googleapis.com

  #     - name: Install nix-eval-jobs
  #       run:  nix profile install nixpkgs#nix-eval-jobs

  #     - run: ./build-and-publish-unchanged.sh
  #       env:
  #         AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID     }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            extra-substituters = s3://muck-intromit-lizard?endpoint=https://storage.googleapis.com
            extra-platforms    = aarch64-linux

      - name: Install nix-eval-jobs
        run:  nix profile install nixpkgs#nix-eval-jobs

      - run: ./build-and-publish-unchanged.sh --argstr system aarch64-linux
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID     }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
